site_name: LEAP Ireland
theme:
  logo: assets/images/leap_ireland.png
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
      plugins:

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tom%C3%A1s-mac-uidhir-92637158/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/MossyMacUidhir

nav:
  - About: index.md
  - Documentation: documentation.md
  - Scenarios: 
        - Introduction: scenarios.md
        - Reference: scenarios\scenarios_desc_ref.md
        - Sectoral Emissions Ceiling: scenarios\scenarios_desc_sec.md
  - Results:
        - Introduction: results.md
        - Reference: results\results_ref.md
        - Sectoral Emissions Ceiling: results\results_sec.md
  


copyright:
  "&copy UCC EPMG"
